# Default values for java-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3

image:
  repository: your-java-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: java-app
  port: 80
  targetPort: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
